# Personalize your website info here
title:            Tara Gunkali Chowdhury
tagline:          'Professional Website for Tara Chowdhury'
description:      'Website and Blog for Tara Chowdhury'
url:              http://taragunkali.github.io
author:
  name:           Tara Gunkali Chowdhury
  url:            https://twitter.com/daaderside

## You don't need to modify below this line
paginate:         5

# Custom vars
version:          2.1.0
github:
  repo:           https://github.com/poole/hyde

gems: [jekyll-paginate,jekyll-gist, redcarpet]
paginate: 5
paginate_path: "page:num"

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
baseurl:          /
